import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createHighlighter } from "shiki";
import type { Plugin } from "vite";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Vite plugin that generates theme colors from Shiki theme.
 * Only regenerates when src/config.ts changes.
 */
export function themeColorsPlugin(): Plugin {
	const configPath = path.resolve(__dirname, "../config.ts");
	const outputPath = path.resolve(__dirname, "../generated/theme-colors.ts");
	let currentTheme: string | null = null;

	async function generateColors(themeName: string) {
		console.log(`[Theme] Generating colors for theme: ${themeName}`);

		const highlighter = await createHighlighter({
			themes: [themeName],
			langs: ["sql"],
		});

		// Use realistic SQL queries to get proper token colors
		const samples = {
			keywords: "SELECT FROM WHERE JOIN ORDER BY",
			realSQL: "SELECT o.order_id, o.customer FROM orders o",
			numbers: "SELECT 123, 45.67 FROM table",
			strings: "SELECT 'hello', \"world\" FROM table",
			comments: "-- This is a comment\nSELECT * FROM table",
			functions: "SELECT COUNT(*), SUM(amount) FROM table",
		};

		// Extract keyword color (SELECT, FROM, etc.)
		const keywordTokens = highlighter.codeToTokens(samples.keywords, {
			lang: "sql",
			theme: themeName,
		});
		const keywordColor =
			keywordTokens.tokens[0]?.find((t) => t.content.trim() === "SELECT")
				?.color || "#ffffff";

		// Extract identifier color using realistic SQL with object references
		const identifierTokens = highlighter.codeToTokens(samples.realSQL, {
			lang: "sql",
			theme: themeName,
		});
		const identifierColor =
			identifierTokens.tokens[0]?.find((t) => t.content.trim() === "o")
				?.color || "#ffffff";

		// Extract number color
		const numberTokens = highlighter.codeToTokens(samples.numbers, {
			lang: "sql",
			theme: themeName,
		});
		const numberColor =
			numberTokens.tokens[0]?.find((t) => t.content.trim() === "123")?.color ||
			identifierColor;

		// Extract string color
		const stringTokens = highlighter.codeToTokens(samples.strings, {
			lang: "sql",
			theme: themeName,
		});
		const stringColor =
			stringTokens.tokens[0]?.find((t) => t.content.includes("'"))?.color ||
			"#ffffff";

		// Extract comment color
		const commentTokens = highlighter.codeToTokens(samples.comments, {
			lang: "sql",
			theme: themeName,
		});
		const commentColor =
			commentTokens.tokens[0]?.find((t) => t.content.includes("--"))?.color ||
			"#888888";

		// Extract special/function color
		const functionTokens = highlighter.codeToTokens(samples.functions, {
			lang: "sql",
			theme: themeName,
		});
		const specialColor =
			functionTokens.tokens[0]?.find((t) =>
				t.content.trim().match(/COUNT|SUM/i),
			)?.color || identifierColor;

		// Generate TypeScript file
		const content = `// AUTO-GENERATED - DO NOT EDIT
// Generated by vite-plugin-theme-colors.ts
// Theme: ${themeName}

export const themeColors = {
  "syntaxKeyword": "${keywordColor}",
  "syntaxIdentifier": "${identifierColor}",
  "syntaxNumber": "${numberColor}",
  "syntaxString": "${stringColor}",
  "syntaxComment": "${commentColor}",
  "syntaxSpecial": "${specialColor}"
} as const;

export type ThemeColors = typeof themeColors;
`;

		// Ensure output directory exists
		const outputDir = path.dirname(outputPath);
		if (!fs.existsSync(outputDir)) {
			fs.mkdirSync(outputDir, { recursive: true });
		}

		fs.writeFileSync(outputPath, content, "utf-8");
		console.log(`[Theme] Generated theme-colors.ts with ${themeName} colors`);
	}

	function extractThemeFromConfig(): string {
		const content = fs.readFileSync(configPath, "utf-8");
		const match = content.match(/theme:\s*["']([^"']+)["']/);
		return match ? match[1] : "github-dark";
	}

	return {
		name: "vite-plugin-theme-colors",

		async buildStart() {
			// Generate colors at the start of build
			const theme = extractThemeFromConfig();
			if (theme !== currentTheme) {
				currentTheme = theme;
				await generateColors(theme);
			}
		},

		async handleHotUpdate({ file, server }) {
			// Regenerate if config.ts changes
			if (file === configPath) {
				const theme = extractThemeFromConfig();
				if (theme !== currentTheme) {
					currentTheme = theme;
					await generateColors(theme);

					// Trigger HMR for files that import theme-colors
					const moduleGraph = server.moduleGraph;
					const module = moduleGraph.getModuleById(outputPath);
					if (module) {
						moduleGraph.invalidateModule(module);
						server.ws.send({
							type: "full-reload",
							path: "*",
						});
					}
				}
			}
		},

		configureServer(server) {
			// Generate colors when dev server starts
			server.httpServer?.once("listening", async () => {
				const theme = extractThemeFromConfig();
				currentTheme = theme;
				await generateColors(theme);
			});
		},
	};
}
